# Generated by Django 3.0.5 on 2020-05-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='info',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='auth_secret',
            field=models.CharField(default='SUPERSECRET', max_length=16, verbose_name='secret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformuser',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
